// This file is auto-generated by @hey-api/openapi-ts

export type BaseResponse_LoginUserVO_ = {
  code?: number;
  data?: LoginUserVO;
  message?: string;
};

export type BaseResponse_Page_PostVO__ = {
  code?: number;
  data?: Page_PostVO_;
  message?: string;
};

export type BaseResponse_Page_Post__ = {
  code?: number;
  data?: Page_Post_;
  message?: string;
};

export type BaseResponse_Page_UserVO__ = {
  code?: number;
  data?: Page_UserVO_;
  message?: string;
};

export type BaseResponse_Page_User__ = {
  code?: number;
  data?: Page_User_;
  message?: string;
};

export type BaseResponse_PostVO_ = {
  code?: number;
  data?: PostVO;
  message?: string;
};

export type BaseResponse_UserVO_ = {
  code?: number;
  data?: UserVO;
  message?: string;
};

export type BaseResponse_User_ = {
  code?: number;
  data?: User;
  message?: string;
};

export type BaseResponse_boolean_ = {
  code?: number;
  data?: boolean;
  message?: string;
};

export type BaseResponse_int_ = {
  code?: number;
  data?: number;
  message?: string;
};

export type BaseResponse_long_ = {
  code?: number;
  data?: number;
  message?: string;
};

export type BaseResponse_string_ = {
  code?: number;
  data?: string;
  message?: string;
};

export type DeleteRequest = {
  id?: number;
};

export type LoginUserVO = {
  createTime?: string;
  id?: number;
  updateTime?: string;
  userAvatar?: string;
  userName?: string;
  userProfile?: string;
  userRole?: string;
};

export type OrderItem = {
  asc?: boolean;
  column?: string;
};

export type Page_PostVO_ = {
  countId?: string;
  current?: number;
  maxLimit?: number;
  optimizeCountSql?: boolean;
  orders?: Array<OrderItem>;
  pages?: number;
  records?: Array<PostVO>;
  searchCount?: boolean;
  size?: number;
  total?: number;
};

export type Page_Post_ = {
  countId?: string;
  current?: number;
  maxLimit?: number;
  optimizeCountSql?: boolean;
  orders?: Array<OrderItem>;
  pages?: number;
  records?: Array<Post>;
  searchCount?: boolean;
  size?: number;
  total?: number;
};

export type Page_UserVO_ = {
  countId?: string;
  current?: number;
  maxLimit?: number;
  optimizeCountSql?: boolean;
  orders?: Array<OrderItem>;
  pages?: number;
  records?: Array<UserVO>;
  searchCount?: boolean;
  size?: number;
  total?: number;
};

export type Page_User_ = {
  countId?: string;
  current?: number;
  maxLimit?: number;
  optimizeCountSql?: boolean;
  orders?: Array<OrderItem>;
  pages?: number;
  records?: Array<User>;
  searchCount?: boolean;
  size?: number;
  total?: number;
};

export type Post = {
  content?: string;
  createTime?: string;
  favourNum?: number;
  id?: number;
  isDelete?: number;
  tags?: string;
  thumbNum?: number;
  title?: string;
  updateTime?: string;
  userId?: number;
};

export type PostAddRequest = {
  content?: string;
  tags?: Array<string>;
  title?: string;
};

export type PostEditRequest = {
  content?: string;
  id?: number;
  tags?: Array<string>;
  title?: string;
};

export type PostFavourAddRequest = {
  postId?: number;
};

export type PostFavourQueryRequest = {
  current?: number;
  pageSize?: number;
  postQueryRequest?: PostQueryRequest;
  sortField?: string;
  sortOrder?: string;
  userId?: number;
};

export type PostQueryRequest = {
  content?: string;
  current?: number;
  favourUserId?: number;
  id?: number;
  notId?: number;
  orTags?: Array<string>;
  pageSize?: number;
  searchText?: string;
  sortField?: string;
  sortOrder?: string;
  tags?: Array<string>;
  title?: string;
  userId?: number;
};

export type PostThumbAddRequest = {
  postId?: number;
};

export type PostUpdateRequest = {
  content?: string;
  id?: number;
  tags?: Array<string>;
  title?: string;
};

export type PostVO = {
  content?: string;
  createTime?: string;
  favourNum?: number;
  hasFavour?: boolean;
  hasThumb?: boolean;
  id?: number;
  tagList?: Array<string>;
  thumbNum?: number;
  title?: string;
  updateTime?: string;
  user?: UserVO;
  userId?: number;
};

export type User = {
  createTime?: string;
  id?: number;
  isDelete?: number;
  mpOpenId?: string;
  unionId?: string;
  updateTime?: string;
  userAccount?: string;
  userAvatar?: string;
  userName?: string;
  userPassword?: string;
  userProfile?: string;
  userRole?: string;
};

export type UserAddRequest = {
  userAccount?: string;
  userAvatar?: string;
  userName?: string;
  userRole?: string;
};

export type UserLoginRequest = {
  userAccount?: string;
  userPassword?: string;
};

export type UserQueryRequest = {
  current?: number;
  id?: number;
  mpOpenId?: string;
  pageSize?: number;
  sortField?: string;
  sortOrder?: string;
  unionId?: string;
  userName?: string;
  userProfile?: string;
  userRole?: string;
};

export type UserRegisterRequest = {
  checkPassword?: string;
  userAccount?: string;
  userPassword?: string;
};

export type UserUpdateMyRequest = {
  userAvatar?: string;
  userName?: string;
  userProfile?: string;
};

export type UserUpdateRequest = {
  id?: number;
  userAvatar?: string;
  userName?: string;
  userProfile?: string;
  userRole?: string;
};

export type UserVO = {
  createTime?: string;
  id?: number;
  userAvatar?: string;
  userName?: string;
  userProfile?: string;
  userRole?: string;
};

export type CheckUsingGetData = {
  query?: {
    /**
     * echostr
     */
    echostr?: string;
    /**
     * nonce
     */
    nonce?: string;
    /**
     * signature
     */
    signature?: string;
    /**
     * timestamp
     */
    timestamp?: string;
  };
};

export type CheckUsingGetResponse = string;

export type CheckUsingGetError = unknown;

export type ReceiveMessageUsingPostResponse = unknown;

export type ReceiveMessageUsingPostError = unknown;

export type UploadFileUsingPostData = {
  query?: {
    biz?: string;
  };
};

export type UploadFileUsingPostResponse = BaseResponse_string_ | unknown;

export type UploadFileUsingPostError = unknown;

export type AddPostUsingPostData = {
  /**
   * postAddRequest
   */
  body: PostAddRequest;
};

export type AddPostUsingPostResponse = BaseResponse_long_ | unknown;

export type AddPostUsingPostError = unknown;

export type DeletePostUsingPostData = {
  /**
   * deleteRequest
   */
  body: DeleteRequest;
};

export type DeletePostUsingPostResponse = BaseResponse_boolean_ | unknown;

export type DeletePostUsingPostError = unknown;

export type EditPostUsingPostData = {
  /**
   * postEditRequest
   */
  body: PostEditRequest;
};

export type EditPostUsingPostResponse = BaseResponse_boolean_ | unknown;

export type EditPostUsingPostError = unknown;

export type GetPostVoByIdUsingGetData = {
  query?: {
    /**
     * id
     */
    id?: number;
  };
};

export type GetPostVoByIdUsingGetResponse = BaseResponse_PostVO_;

export type GetPostVoByIdUsingGetError = unknown;

export type ListPostByPageUsingPostData = {
  /**
   * postQueryRequest
   */
  body: PostQueryRequest;
};

export type ListPostByPageUsingPostResponse =
  | BaseResponse_Page_Post__
  | unknown;

export type ListPostByPageUsingPostError = unknown;

export type ListPostVoByPageUsingPostData = {
  /**
   * postQueryRequest
   */
  body: PostQueryRequest;
};

export type ListPostVoByPageUsingPostResponse =
  | BaseResponse_Page_PostVO__
  | unknown;

export type ListPostVoByPageUsingPostError = unknown;

export type ListMyPostVoByPageUsingPostData = {
  /**
   * postQueryRequest
   */
  body: PostQueryRequest;
};

export type ListMyPostVoByPageUsingPostResponse =
  | BaseResponse_Page_PostVO__
  | unknown;

export type ListMyPostVoByPageUsingPostError = unknown;

export type SearchPostVoByPageUsingPostData = {
  /**
   * postQueryRequest
   */
  body: PostQueryRequest;
};

export type SearchPostVoByPageUsingPostResponse =
  | BaseResponse_Page_PostVO__
  | unknown;

export type SearchPostVoByPageUsingPostError = unknown;

export type UpdatePostUsingPostData = {
  /**
   * postUpdateRequest
   */
  body: PostUpdateRequest;
};

export type UpdatePostUsingPostResponse = BaseResponse_boolean_ | unknown;

export type UpdatePostUsingPostError = unknown;

export type DoPostFavourUsingPostData = {
  /**
   * postFavourAddRequest
   */
  body: PostFavourAddRequest;
};

export type DoPostFavourUsingPostResponse = BaseResponse_int_ | unknown;

export type DoPostFavourUsingPostError = unknown;

export type ListFavourPostByPageUsingPostData = {
  /**
   * postFavourQueryRequest
   */
  body: PostFavourQueryRequest;
};

export type ListFavourPostByPageUsingPostResponse =
  | BaseResponse_Page_PostVO__
  | unknown;

export type ListFavourPostByPageUsingPostError = unknown;

export type ListMyFavourPostByPageUsingPostData = {
  /**
   * postQueryRequest
   */
  body: PostQueryRequest;
};

export type ListMyFavourPostByPageUsingPostResponse =
  | BaseResponse_Page_PostVO__
  | unknown;

export type ListMyFavourPostByPageUsingPostError = unknown;

export type DoThumbUsingPostData = {
  /**
   * postThumbAddRequest
   */
  body: PostThumbAddRequest;
};

export type DoThumbUsingPostResponse = BaseResponse_int_ | unknown;

export type DoThumbUsingPostError = unknown;

export type SetMenuUsingGetResponse = string;

export type SetMenuUsingGetError = unknown;

export type AddUserUsingPostData = {
  /**
   * userAddRequest
   */
  body: UserAddRequest;
};

export type AddUserUsingPostResponse = BaseResponse_long_ | unknown;

export type AddUserUsingPostError = unknown;

export type DeleteUserUsingPostData = {
  /**
   * deleteRequest
   */
  body: DeleteRequest;
};

export type DeleteUserUsingPostResponse = BaseResponse_boolean_ | unknown;

export type DeleteUserUsingPostError = unknown;

export type GetUserByIdUsingGetData = {
  query?: {
    /**
     * id
     */
    id?: number;
  };
};

export type GetUserByIdUsingGetResponse = BaseResponse_User_;

export type GetUserByIdUsingGetError = unknown;

export type GetLoginUserUsingGetResponse = BaseResponse_LoginUserVO_;

export type GetLoginUserUsingGetError = unknown;

export type GetUserVoByIdUsingGetData = {
  query?: {
    /**
     * id
     */
    id?: number;
  };
};

export type GetUserVoByIdUsingGetResponse = BaseResponse_UserVO_;

export type GetUserVoByIdUsingGetError = unknown;

export type ListUserByPageUsingPostData = {
  /**
   * userQueryRequest
   */
  body: UserQueryRequest;
};

export type ListUserByPageUsingPostResponse =
  | BaseResponse_Page_User__
  | unknown;

export type ListUserByPageUsingPostError = unknown;

export type ListUserVoByPageUsingPostData = {
  /**
   * userQueryRequest
   */
  body: UserQueryRequest;
};

export type ListUserVoByPageUsingPostResponse =
  | BaseResponse_Page_UserVO__
  | unknown;

export type ListUserVoByPageUsingPostError = unknown;

export type UserLoginUsingPostData = {
  /**
   * userLoginRequest
   */
  body: UserLoginRequest;
};

export type UserLoginUsingPostResponse = BaseResponse_LoginUserVO_ | unknown;

export type UserLoginUsingPostError = unknown;

export type UserLoginByWxOpenUsingGetData = {
  query: {
    /**
     * code
     */
    code: string;
  };
};

export type UserLoginByWxOpenUsingGetResponse = BaseResponse_LoginUserVO_;

export type UserLoginByWxOpenUsingGetError = unknown;

export type UserLogoutUsingPostResponse = BaseResponse_boolean_ | unknown;

export type UserLogoutUsingPostError = unknown;

export type UserRegisterUsingPostData = {
  /**
   * userRegisterRequest
   */
  body: UserRegisterRequest;
};

export type UserRegisterUsingPostResponse = BaseResponse_long_ | unknown;

export type UserRegisterUsingPostError = unknown;

export type UpdateUserUsingPostData = {
  /**
   * userUpdateRequest
   */
  body: UserUpdateRequest;
};

export type UpdateUserUsingPostResponse = BaseResponse_boolean_ | unknown;

export type UpdateUserUsingPostError = unknown;

export type UpdateMyUserUsingPostData = {
  /**
   * userUpdateMyRequest
   */
  body: UserUpdateMyRequest;
};

export type UpdateMyUserUsingPostResponse = BaseResponse_boolean_ | unknown;

export type UpdateMyUserUsingPostError = unknown;
